version: "3"
services: 
  drupal:
    image: drupal:latest
    ports:
      - "5001:5000"
    restart: always
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    ports: 
      - "5002:5000"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgresql_data:/var/lib/postgresql/data
volumes: 
  postgresql_data:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:

